---
- name: Ensure {{ locale }} locale exists
  locale_gen:
    name: "{{ locale }}"
    state: present
- name: Set system locale
  template:
    src: locale.conf.j2
    dest: /etc/locale.conf
    mode: '0644'
