---
- name: Ensure {{ value }} locale exists
  locale_gen:
    name: "{{ value }}"
    state: present
  vars:
    value: "{{ locale | default(system_locale) }}"
- name: Set system locale
  template:
    src: locale.conf.j2
    dest: /etc/locale.conf
    mode: '0644'
  when: locale is not defined
