---
- include_tasks: download.yml
  vars:
    date: "{{ '%Y.%m.01' | strftime }}"
  args:
    apply:
      ignore_errors: yes
- name: Fallback to previous month release
  include_tasks: download.yml
  vars:
    date: "{{ ansible_date_time.date | to_datetime('%Y-%m-%d') | day_one(months_back=1) }}"
  when: download_result is failed
- name: Create an empty container
  command: buildah from scratch
  register: buildah_from
  changed_when: buildah_from.stdout | length > 0
- name: "{{ buildah_from.stdout }} created"
  set_fact:
    working_container: "{{ buildah_from.stdout }}"
    cacheable: yes
- name: Mount {{ working_container }}
  command: buildah mount {{ working_container }}
  register: buildah_mount
  changed_when: buildah_mount.stdout | length > 0
- name: Create root filesystem
  unarchive:
    src: "{{ download_path }}/archlinux-bootstrap.tar.gz"
    dest: "{{ buildah_mount.stdout }}"
    extra_opts:
      - --strip-components=1
      - --xattrs
      - --numeric-owner
- name: Copy list of pacman mirrors
  template:
    src: mirrorlist.j2
    dest: "{{ buildah_mount.stdout }}/etc/pacman.d/mirrorlist"
    mode: '0644'
    backup: yes
- name: Copy pacman configuration
  copy:
    src: pacman.conf
    dest: "{{ buildah_mount.stdout }}/etc/"
    mode: '0644'
    backup: yes
