---
- name: Bind mount host /dev inside container
  mount:
    path: "{{ buildah_mount.stdout }}/dev"
    src: /dev
    opts: bind,ro
    fstype: none
    fstab: /tmp/fstab.dummy
    state: mounted
- name: Init pacman keyring
  command:
    argv:
      - unshare
      - --fork
      - --pid
      - chroot
      - "{{ buildah_mount.stdout }}"
      - /usr/bin/pacman-key
      - --init
  register: pacman_key_init
  changed_when: pacman_key_init.stdout | length > 0
  failed_when: >
    (pacman_key_init.rc == 1) or
    (pacman_key_init.stderr is search('key generation failed'))
- name: Populate with keys of all official packagers
  command:
    argv:
      - unshare
      - --fork
      - --pid
      - chroot
      - "{{ buildah_mount.stdout }}"
      - /usr/bin/pacman-key
      - --populate
      - archlinux
  changed_when: true
