---
- name: Init pacman keyring
  command: chroot {{ buildah_mount.stdout }} /usr/bin/pacman-key --init
  register: pacman_key_init
  changed_when: pacman_key_init.stdout | length > 0
- name: Populate with keys of all official packagers
  command: chroot {{ buildah_mount.stdout }} /usr/bin/pacman-key --populate archlinux
  changed_when: true
