---
- name: Touch files for devices
  file:
    path: &mount_point "{{ buildah_mount.stdout }}/dev/{{ item }}"
    state: touch
  loop: &loop_devices
    - random
    - urandom
- name: Bind mount required devices
  mount:
    path: *mount_point
    src: /dev/{{ item }}
    opts: bind
    fstype: none
    fstab: /tmp/fstab.dummy
    state: mounted
  loop: *loop_devices
- name: Init pacman keyring
  command:
    argv:
      - unshare
      - --fork
      - --pid
      - chroot
      - "{{ buildah_mount.stdout }}"
      - /usr/bin/pacman-key
      - --init
  register: pacman_key_init
  changed_when: pacman_key_init.stdout | length > 0
  failed_when: >
    (pacman_key_init.rc == 1) or
    (pacman_key_init.stderr is search('key generation failed'))
- name: Populate with keys of all official packagers
  command:
    argv:
      - unshare
      - --fork
      - --pid
      - chroot
      - "{{ buildah_mount.stdout }}"
      - /usr/bin/pacman-key
      - --populate
      - archlinux
  changed_when: true
- name: Unmount devices
  mount:
    path: *mount_point
    fstab: /tmp/fstab.dummy
    state: unmounted
  loop: *loop_devices
- name: Remove mount points
  file:
    path: *mount_point
    state: absent
  loop: *loop_devices
