---
name: arch_container

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint role arch_container
        uses: ansible/ansible-lint-action@v4.1.0
        with:
          targets: containers/archlinux
